---
title: Amazon Mechanical Turk in cMAP-CEMNL, part 1
author: Patrick Sadil
date: '2018-07-20'
slug: mechanical-turk-part-I
categories:
  - experiments
tags:
  - python
  - psiturk
  - mturk
  - jspsych
header:
  caption: ''
  image: ''
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, warning = FALSE)
```

# Goals

1. Provide high-level overview of the tools used to run an MTurk study
2. Highlight steps at which to be careful while setting the study up

Part 2 will cover a basic project

# The current lab practice is to string together many different tools


Setting up a study on MTurk can roughly be divided into three needs. 


* We need some way to code the experiment 
  + Packages
    - [jspsych](https://www.jspsych.org)
    - jquery [w3schools](https://www.w3schools.com/jquery/default.asp)
  + Languages
    - Javascript [w3schools](https://www.w3schools.com/js/default.asp)
    - CSS [w3schools](https://www.w3schools.com/css/default.asp)
    - HTML [w3schools](https://www.w3schools.com/html/default.asp)
  + Useful concepts
    - Turns out that, in javascript, line 2 might not run after line 1! It's helpful to read about [asynchronous programming in javascript](https://javascript.info/callbacks)
    - [Static sites, dynamic sites, and static site generators](https://about.gitlab.com/2016/06/03/ssg-overview-gitlab-pages-part-1-dynamic-x-static/)
    
* We need some way to organize that experimental code such that it is advertised to turkers, Amazon is informed when a Turker finishes the experiment, their responses are stored in a database, and we can approve the turkers' work 
  + Packages
    - [psiturk](https://psiturk.readthedocs.io/en/latest/)
    - [flask](https://flask.palletsprojects.com/en/2.0.x/)
    - [jinja](https://www.palletsprojects.com/p/jinja/)
  + Languages
    - [Python](https://python.swaroopch.com/), [Anaconda distribution](https://www.anaconda.com/download/)
    - [SQLite](https://cran.r-project.org/web/packages/dbplyr/vignettes/dbplyr.html)
  + Useful concepts
    - [what is a database?](https://taylorwhitten.github.io/blog/RSQLite1)
    - [what is an ip address?](https://www.howtogeek.com/66214/how-to-forward-ports-on-your-router/)
    - Psiturk runs on python 2, not python 3. You may want to be using an [Anaconda virtual environment](https://conda.io/docs/user-guide/tasks/manage-environments.html)

* We need a server to host the above components such that they are accessible via an internet connection 
  + Services
    - Amazon Mechanical Turk: follow the [psiturk documentation!](https://psiturk.readthedocs.io/en/latest/amt_setup.html#)
    - Amazon EC2: follow the [psiturk documentation!](https://psiturk.readthedocs.io/en/latest/amazon_ec2.html)
  + useful concepts
    - definitely keep the psiturk documentation open in a tab somewhere

In reverse, the EC2 instance is the server that will host the experiment. Psiturk organizes a bunch of packages (which are primarily written in python) to function as the 'backend,' coordinating the different webpages that the turk worker will see. Although psiturk also includes a javascript library that could be used to write the actual experiment, it will probably be much easier to write the experiment with the jspsych package.

At the next deeper level, it's useful to know how HTML, javascript, and CSS work to make websites run.

Next, the template part comes from the idea of a static site generator. The particular SSG is jinja. It's useful to know about Flask, because the Flask syntax defines custom routes (e.g., helping determine which stimuli to show a given participant). Jinja might be useful, but I haven't found it necessary to know more than the basics of what is an SSG.

[Todd Gureckis' videotapped course lectures](https://gureckislab.org/courses/spring14/online_data_collection/)
[Tim Brady's Mechanical Turk Tutorial](https://bradylab.ucsd.edu/ttt/index.html)
[Wilma Bainbridge organized a Big Data Tutorial at VSS 2018](https://wilmabainbridge.com/bigdataclass.html). Note, this involves the package psitoolkit. That seemed like an okay alternative, but I worried that I would encounter a situation that psitoolkit wasn't equipped to handle and would be stuck. Working with the psiturk + jspsych ensured that there would be the flexibility to run pretty much any kind of experiment

# Gotcha's and extra notes

* Psiturk runs on python 2, not 3. If you're trying to install psiturk and you immediately start getting errors, make sure to check which python version you're on

* when setting up EC2, pay careful attention to the IP configuration settings. To be able to use ssh to access the instance, you'll need to have your IP address match the IP it's expecting. Or, just set it to receive traffic from 'Anywhere.' Likewise, make sure that the custom TCP is set to receive traffic from Anywhere

* Do read the tutorial on [asynchronous programming in javascript](https://javascript.info/callbacks). It can be really confusing when you're trying to debug and variables aren't defined

* Speaking of debugging, your friend will be the 'developer tools' in whatever browser you're using. Right click on the experiment and check 'view source' to get access to a console

* Using the psiturk `debug` command will attempt to open up the experiment in the browser. This will only work if no browser is currently open.

* if an experiment involves a lot of media, the media can be optimized a bit using something like [optipng](http://optipng.sourceforge.net/). This keeps the png looking fine but decreases load time

