#:schema https://panache.bz/panache.schema.json

[format]
line-width = 100
wrap = "preserve"

[lint.rules]
missing-chunk-labels = false

[formatters]
python = "ruff"
r = "air"

[linters]
python = "ruff"
r = "jarl"
