project:
  type: website

website:
  title: "psadil"
  google-analytics: G-SP0TP763NP
  navbar:
    left:
      - href: https://scholar.google.com/citations?user=HhPeElcAAAAJ
        text: Publications
      - posts.qmd

format:
  html:
    header-includes: |
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    highlight-style: atom-one
    theme:
      light: [flatly, static/custom.scss]
      dark: [solar, static/custom.scss]
    toc: true
    respect-user-color-scheme: true
    
