#:schema https://pixi.sh/v0.73.0/schema/manifest/schema.json

[workspace]
authors = [ "Patrick Sadil <psadil@gmail.com>" ]
channels = [ "conda-forge" ]
name = "2019-11-15-half-of-a-parameter"
platforms = [ "osx-arm64" ]
version = "0.1.0"

[tasks]
render = "quarto render index.qmd"

[dependencies]
quarto = ">=1.9.38,<2"
