[workspace]
authors = ["Patrick Sadil <psadil@gmail.com>"]
channels = ["conda-forge"]
name = "2022-04-23-tf-dataset-from-3d-nifti"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
render = "quarto render index.qmd"

[dependencies]
numpy = ">=2.3.1,<3"
tensorflow = ">=2.18.0,<3"
nibabel = ">=5.3.2,<6"
nilearn = ">=0.12.0,<0.13"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.10.3,<4"
deno = ">=1.46.3,<1.47"
