#:schema https://pixi.sh/v0.73.0/schema/manifest/schema.json

[workspace]
authors = [ "Patrick Sadil <psadil@gmail.com>" ]
channels = [ "conda-forge" ]
name = "2018-06-05-eyetracking-with-eyelink-in-psychtoolbox"
platforms = [ "osx-arm64" ]
version = "0.1.0"

[tasks]
render = "quarto render index.qmd"

[dependencies]
quarto = ">=1.9.38,<2"
r-base = ">=4.5.3,<4.6"
r-knitr = ">=1.51,<2"
r-rmarkdown = ">=2.31,<3"
