on:
  push:
    branches:
      - main

name: blogdown

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3' # The Go version to download (if necessary) and use.

      - name: setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.0'

      - uses: r-lib/actions/setup-pandoc@v1

      - name: cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: install external libs
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libmagick++-dev cargo

      - name: install R packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: install hugo
        run: |
          R -e 'blogdown::install_hugo("0.81.0")'

      - name: cache build
        uses: actions/cache@v2
        with:
          path: |
            content/post/**/*html
            content/post/**/*_files/**/*
            content/post/**/*_cache/**/*
          key: blogdown-${{ hashFiles('**/blogdown/md5sum.txt') }}

      - name: build
        run: |
          R -e 'blogdown::build_site(TRUE, build_rmd = "md5sum")'

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
