on:
  push:
    branches:
      - main

name: blogdown

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3' # The Go version to download (if necessary) and use.

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: install external libs
        run: sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libmagick++-dev cargo libcurl4-openssl-dev 

      - uses: r-lib/actions/setup-renv@v2

      - name: install hugo
        run: |
          R -e 'blogdown::install_hugo("0.83.1")'

      - name: build
        shell: Rscript {0}
        run: |
          blogdown::build_site(TRUE, build_rmd = builder)

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
